# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hydra.proto.service import context_ops_pb2 as hydra_dot_proto_dot_service_dot_context__ops__pb2


class ContextOpsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reset = channel.unary_unary(
                '/hydra.service.ContextOps/reset',
                request_serializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.ResetRequest.SerializeToString,
                response_deserializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.ResetReply.FromString,
                )
        self.init = channel.unary_unary(
                '/hydra.service.ContextOps/init',
                request_serializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.InitRequest.SerializeToString,
                response_deserializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.InitReply.FromString,
                )
        self.setup_przs_generators = channel.unary_unary(
                '/hydra.service.ContextOps/setup_przs_generators',
                request_serializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.SetupPRZSGeneratorsRequest.SerializeToString,
                response_deserializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.SetupPRZSGeneratorsReply.FromString,
                )
        self.share_secret = channel.unary_unary(
                '/hydra.service.ContextOps/share_secret',
                request_serializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.ShareSecretRequest.SerializeToString,
                response_deserializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.ShareSecretReply.FromString,
                )
        self.generate_przs = channel.unary_unary(
                '/hydra.service.ContextOps/generate_przs',
                request_serializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.GeneratePRZSRequest.SerializeToString,
                response_deserializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.GeneratePRZSReply.FromString,
                )


class ContextOpsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setup_przs_generators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def share_secret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def generate_przs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextOpsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reset': grpc.unary_unary_rpc_method_handler(
                    servicer.reset,
                    request_deserializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.ResetRequest.FromString,
                    response_serializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.ResetReply.SerializeToString,
            ),
            'init': grpc.unary_unary_rpc_method_handler(
                    servicer.init,
                    request_deserializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.InitRequest.FromString,
                    response_serializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.InitReply.SerializeToString,
            ),
            'setup_przs_generators': grpc.unary_unary_rpc_method_handler(
                    servicer.setup_przs_generators,
                    request_deserializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.SetupPRZSGeneratorsRequest.FromString,
                    response_serializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.SetupPRZSGeneratorsReply.SerializeToString,
            ),
            'share_secret': grpc.unary_unary_rpc_method_handler(
                    servicer.share_secret,
                    request_deserializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.ShareSecretRequest.FromString,
                    response_serializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.ShareSecretReply.SerializeToString,
            ),
            'generate_przs': grpc.unary_unary_rpc_method_handler(
                    servicer.generate_przs,
                    request_deserializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.GeneratePRZSRequest.FromString,
                    response_serializer=hydra_dot_proto_dot_service_dot_context__ops__pb2.GeneratePRZSReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra.service.ContextOps', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContextOps(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hydra.service.ContextOps/reset',
            hydra_dot_proto_dot_service_dot_context__ops__pb2.ResetRequest.SerializeToString,
            hydra_dot_proto_dot_service_dot_context__ops__pb2.ResetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hydra.service.ContextOps/init',
            hydra_dot_proto_dot_service_dot_context__ops__pb2.InitRequest.SerializeToString,
            hydra_dot_proto_dot_service_dot_context__ops__pb2.InitReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setup_przs_generators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hydra.service.ContextOps/setup_przs_generators',
            hydra_dot_proto_dot_service_dot_context__ops__pb2.SetupPRZSGeneratorsRequest.SerializeToString,
            hydra_dot_proto_dot_service_dot_context__ops__pb2.SetupPRZSGeneratorsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def share_secret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hydra.service.ContextOps/share_secret',
            hydra_dot_proto_dot_service_dot_context__ops__pb2.ShareSecretRequest.SerializeToString,
            hydra_dot_proto_dot_service_dot_context__ops__pb2.ShareSecretReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def generate_przs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hydra.service.ContextOps/generate_przs',
            hydra_dot_proto_dot_service_dot_context__ops__pb2.GeneratePRZSRequest.SerializeToString,
            hydra_dot_proto_dot_service_dot_context__ops__pb2.GeneratePRZSReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
