# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydra/proto/service/context_ops.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hydra.proto.context import context_pb2 as hydra_dot_proto_dot_context_dot_context__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%hydra/proto/service/context_ops.proto\x12\rhydra.service\x1a!hydra/proto/context/context.proto\"\x0e\n\x0cResetRequest\"\x0c\n\nResetReply\"6\n\x0bInitRequest\x12\'\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x16.hydra.context.Context\"\x1f\n\tInitReply\x12\x12\n\nis_success\x18\x01 \x01(\x08\",\n\x1aSetupPRZSGeneratorsRequest\x12\x0e\n\x06\x63tx_id\x18\x01 \x01(\r\".\n\x18SetupPRZSGeneratorsReply\x12\x12\n\nis_success\x18\x01 \x01(\x08\"0\n\x12ShareSecretRequest\x12\x0e\n\x06\x63tx_id\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\t\"\x1f\n\x10ShareSecretReply\x12\x0b\n\x03ids\x18\x01 \x03(\t\"4\n\x13GeneratePRZSRequest\x12\x0e\n\x06\x63tx_id\x18\x01 \x01(\r\x12\r\n\x05shape\x18\x02 \x03(\r\"\x1f\n\x11GeneratePRZSReply\x12\n\n\x02id\x18\x01 \x01(\t2\xad\x03\n\nContextOps\x12\x41\n\x05reset\x12\x1b.hydra.service.ResetRequest\x1a\x19.hydra.service.ResetReply\"\x00\x12>\n\x04init\x12\x1a.hydra.service.InitRequest\x1a\x18.hydra.service.InitReply\"\x00\x12m\n\x15setup_przs_generators\x12).hydra.service.SetupPRZSGeneratorsRequest\x1a\'.hydra.service.SetupPRZSGeneratorsReply\"\x00\x12T\n\x0cshare_secret\x12!.hydra.service.ShareSecretRequest\x1a\x1f.hydra.service.ShareSecretReply\"\x00\x12W\n\rgenerate_przs\x12\".hydra.service.GeneratePRZSRequest\x1a .hydra.service.GeneratePRZSReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hydra.proto.service.context_ops_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESETREQUEST._serialized_start=91
  _RESETREQUEST._serialized_end=105
  _RESETREPLY._serialized_start=107
  _RESETREPLY._serialized_end=119
  _INITREQUEST._serialized_start=121
  _INITREQUEST._serialized_end=175
  _INITREPLY._serialized_start=177
  _INITREPLY._serialized_end=208
  _SETUPPRZSGENERATORSREQUEST._serialized_start=210
  _SETUPPRZSGENERATORSREQUEST._serialized_end=254
  _SETUPPRZSGENERATORSREPLY._serialized_start=256
  _SETUPPRZSGENERATORSREPLY._serialized_end=302
  _SHARESECRETREQUEST._serialized_start=304
  _SHARESECRETREQUEST._serialized_end=352
  _SHARESECRETREPLY._serialized_start=354
  _SHARESECRETREPLY._serialized_end=385
  _GENERATEPRZSREQUEST._serialized_start=387
  _GENERATEPRZSREQUEST._serialized_end=439
  _GENERATEPRZSREPLY._serialized_start=441
  _GENERATEPRZSREPLY._serialized_end=472
  _CONTEXTOPS._serialized_start=475
  _CONTEXTOPS._serialized_end=904
# @@protoc_insertion_point(module_scope)
