# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hydra.proto.service import crypto_ops_pb2 as hydra_dot_proto_dot_service_dot_crypto__ops__pb2


class CryptoOpsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.init_przs_generators = channel.unary_unary(
                '/hydra.crypto.CryptoOps/init_przs_generators',
                request_serializer=hydra_dot_proto_dot_service_dot_crypto__ops__pb2.InitPRZSGeneratorRequest.SerializeToString,
                response_deserializer=hydra_dot_proto_dot_service_dot_crypto__ops__pb2.InitPRZSGeneratorReply.FromString,
                )


class CryptoOpsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def init_przs_generators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CryptoOpsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'init_przs_generators': grpc.unary_unary_rpc_method_handler(
                    servicer.init_przs_generators,
                    request_deserializer=hydra_dot_proto_dot_service_dot_crypto__ops__pb2.InitPRZSGeneratorRequest.FromString,
                    response_serializer=hydra_dot_proto_dot_service_dot_crypto__ops__pb2.InitPRZSGeneratorReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra.crypto.CryptoOps', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CryptoOps(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def init_przs_generators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hydra.crypto.CryptoOps/init_przs_generators',
            hydra_dot_proto_dot_service_dot_crypto__ops__pb2.InitPRZSGeneratorRequest.SerializeToString,
            hydra_dot_proto_dot_service_dot_crypto__ops__pb2.InitPRZSGeneratorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
