# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydra/proto/service/crypto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n hydra/proto/service/crypto.proto\x12\x0chydra.crypto\"\x1a\n\x18InitPRZSGeneratorRequest\",\n\x16InitPRZSGeneratorReply\x12\x12\n\nis_success\x18\x01 \x01(\x08\x32s\n\tCryptoOps\x12\x66\n\x14init_przs_generators\x12&.hydra.crypto.InitPRZSGeneratorRequest\x1a$.hydra.crypto.InitPRZSGeneratorReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hydra.proto.service.crypto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INITPRZSGENERATORREQUEST._serialized_start=50
  _INITPRZSGENERATORREQUEST._serialized_end=76
  _INITPRZSGENERATORREPLY._serialized_start=78
  _INITPRZSGENERATORREPLY._serialized_end=122
  _CRYPTOOPS._serialized_start=124
  _CRYPTOOPS._serialized_end=239
# @@protoc_insertion_point(module_scope)
