# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hydra.proto.service import share_tensor_ops_pb2 as hydra_dot_proto_dot_service_dot_share__tensor__ops__pb2


class ShareTensorOpsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.compute = channel.unary_unary(
                '/hydra.proto.ceva.service.ShareTensorOps/compute',
                request_serializer=hydra_dot_proto_dot_service_dot_share__tensor__ops__pb2.ComputeRequest.SerializeToString,
                response_deserializer=hydra_dot_proto_dot_service_dot_share__tensor__ops__pb2.ComputeReply.FromString,
                )


class ShareTensorOpsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def compute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShareTensorOpsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'compute': grpc.unary_unary_rpc_method_handler(
                    servicer.compute,
                    request_deserializer=hydra_dot_proto_dot_service_dot_share__tensor__ops__pb2.ComputeRequest.FromString,
                    response_serializer=hydra_dot_proto_dot_service_dot_share__tensor__ops__pb2.ComputeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydra.proto.ceva.service.ShareTensorOps', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShareTensorOps(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hydra.proto.ceva.service.ShareTensorOps/compute',
            hydra_dot_proto_dot_service_dot_share__tensor__ops__pb2.ComputeRequest.SerializeToString,
            hydra_dot_proto_dot_service_dot_share__tensor__ops__pb2.ComputeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
