# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydra/proto/service/share_tensor_ops.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*hydra/proto/service/share_tensor_ops.proto\x12\x18hydra.proto.ceva.service\"(\n\x0e\x43omputeRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02op\x18\x02 \x01(\t\"\x1a\n\x0c\x43omputeReply\x12\n\n\x02id\x18\x01 \x01(\t2o\n\x0eShareTensorOps\x12]\n\x07\x63ompute\x12(.hydra.proto.ceva.service.ComputeRequest\x1a&.hydra.proto.ceva.service.ComputeReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hydra.proto.service.share_tensor_ops_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPUTEREQUEST._serialized_start=72
  _COMPUTEREQUEST._serialized_end=112
  _COMPUTEREPLY._serialized_start=114
  _COMPUTEREPLY._serialized_end=140
  _SHARETENSOROPS._serialized_start=142
  _SHARETENSOROPS._serialized_end=253
# @@protoc_insertion_point(module_scope)
