# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydra/proto/service/store_ops.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hydra.proto.tensor import tensor_pb2 as hydra_dot_proto_dot_tensor_dot_tensor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#hydra/proto/service/store_ops.proto\x12\rhydra.service\x1a\x1fhydra/proto/tensor/tensor.proto\"!\n\x0c\x43learRequest\x12\x11\n\tclient_id\x18\x01 \x01(\r\"\x0c\n\nClearReply\"+\n\nGetRequest\x12\x11\n\tclient_id\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\t\"0\n\x08GetReply\x12$\n\x06tensor\x18\x01 \x01(\x0b\x32\x14.hydra.tensor.Tensor\"G\n\x0cStoreRequest\x12\x11\n\tclient_id\x18\x01 \x01(\r\x12$\n\x06tensor\x18\x02 \x01(\x0b\x32\x14.hydra.tensor.Tensor\"\x18\n\nStoreReply\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x0bViewRequest\x12\x11\n\tclient_id\x18\x01 \x01(\r\"\x18\n\tViewReply\x12\x0b\n\x03ids\x18\x01 \x03(\t2\x8d\x02\n\x08StoreOps\x12\x41\n\x05\x63lear\x12\x1b.hydra.service.ClearRequest\x1a\x19.hydra.service.ClearReply\"\x00\x12;\n\x03get\x12\x19.hydra.service.GetRequest\x1a\x17.hydra.service.GetReply\"\x00\x12\x41\n\x05store\x12\x1b.hydra.service.StoreRequest\x1a\x19.hydra.service.StoreReply\"\x00\x12>\n\x04view\x12\x1a.hydra.service.ViewRequest\x1a\x18.hydra.service.ViewReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hydra.proto.service.store_ops_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLEARREQUEST._serialized_start=87
  _CLEARREQUEST._serialized_end=120
  _CLEARREPLY._serialized_start=122
  _CLEARREPLY._serialized_end=134
  _GETREQUEST._serialized_start=136
  _GETREQUEST._serialized_end=179
  _GETREPLY._serialized_start=181
  _GETREPLY._serialized_end=229
  _STOREREQUEST._serialized_start=231
  _STOREREQUEST._serialized_end=302
  _STOREREPLY._serialized_start=304
  _STOREREPLY._serialized_end=328
  _VIEWREQUEST._serialized_start=330
  _VIEWREQUEST._serialized_end=362
  _VIEWREPLY._serialized_start=364
  _VIEWREPLY._serialized_end=388
  _STOREOPS._serialized_start=391
  _STOREOPS._serialized_end=660
# @@protoc_insertion_point(module_scope)
