# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydra/proto/communication/client.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hydra.proto.communication.grpc import client_pb2 as hydra_dot_proto_dot_communication_dot_grpc_dot_client__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&hydra/proto/communication/client.proto\x12\x13hydra.communication\x1a+hydra/proto/communication/grpc/client.proto\"J\n\x06\x43lient\x12\x36\n\x0bgrpc_client\x18\x01 \x01(\x0b\x32\x1f.hydra.communication.GRPCClientH\x00\x42\x08\n\x06\x63lientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hydra.proto.communication.client_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENT._serialized_start=108
  _CLIENT._serialized_end=182
# @@protoc_insertion_point(module_scope)
